### ISSUE TITLE
Cool.

### ISSUE THREAD

**Issue by ashcel** [KasRoudra/autoreport#2]
Cool. It's not working at all, I've decode the compressed script, found out there's no such things as database or facebook api-related programming. It's purely script kiddie, no report were sent to facebook, just print outing some text.

I'm well surprised if there's actual script out there, but apparently, there is not.

Might useful to impress your friend but it's not working at all.

**Comment by KasRoudra** [comment]
Yeap, you are right. It is useful to impress others.
