### ISSUE TITLE
HOW TO KNOW IF THIS IS WORKING?

### ISSUE THREAD

**Issue by Agrak420** [KasRoudra/autoreport#3]
IS THIS REALLY WORKING SIR? HOW DOES IT WORK?

**Comment by Agrak420** [comment]
total reports done:67

**Comment by NadirAli01** [comment]
idk its working or not let me try !

**Comment by Agrak420** [comment]
any updates on your try sir?

**Comment by KasRoudra** [comment]
Working. Read the README.md. **AUTOREPORT DOES NOT DISABLE ACCOUNT UNLESS THERE IS SPECIFIC POST(S) VIOLATING FACEBOOK COMMUNITY GUIDELINE. If there is such post, autoreport may be able disable that account.**
